# Generated by Django 5.2.12 on 2026-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_address_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Telegram Chat ID"
            ),
        ),
    ]
