# Generated by Django 5.2.12 on 2026-03-25 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeBerry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_berry', models.CharField(max_length=15, verbose_name='Ягоды')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Ягода',
                'verbose_name_plural': 'Ягоды',
            },
        ),
        migrations.CreateModel(
            name='CakeDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_decor', models.CharField(max_length=15, verbose_name='Декор')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Декор',
                'verbose_name_plural': 'Декор',
            },
        ),
        migrations.CreateModel(
            name='CakeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество уровней')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Уровень торта',
                'verbose_name_plural': 'Уровни торта',
            },
        ),
        migrations.CreateModel(
            name='CakeShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=50, verbose_name='Форма')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Форма торта',
                'verbose_name_plural': 'Формы торта',
            },
        ),
        migrations.CreateModel(
            name='CakeTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_topping', models.CharField(max_length=50, verbose_name='Топпинг')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Топпинг',
                'verbose_name_plural': 'Топпинги',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.CharField(blank=True, max_length=200, verbose_name='Надпись на торте')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('berry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berries', to='catalog.cakeberry', verbose_name='Ягоды')),
                ('decor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decors', to='catalog.cakedecor', verbose_name='Декор')),
                ('level_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='catalog.cakelevel', verbose_name='Количество уровней торта')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='catalog.cakeshape', verbose_name='Форма торта')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='catalog.caketopping', verbose_name='Топпинг')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
    ]
