# Generated by Django 5.2.12 on 2026-03-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CakeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("level", "Количество уровней"),
                            ("shape", "Форма"),
                            ("topping", "Топпинг"),
                            ("berry", "Ягоды"),
                            ("decor", "Декор"),
                        ],
                        max_length=20,
                        verbose_name="Тип опции",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("price", models.PositiveIntegerField(verbose_name="Стоимость")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция торта",
                "verbose_name_plural": "Опции торта",
                "ordering": ("kind", "sort_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "name"),
                        name="catalog_cakeoption_kind_name_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CatalogCake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="Slug"),
                ),
                (
                    "occasion",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Повод"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="catalog/cakes/", verbose_name="Изображение"
                    ),
                ),
                (
                    "base_price",
                    models.PositiveIntegerField(verbose_name="Базовая цена"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Торт из каталога",
                "verbose_name_plural": "Торты из каталога",
                "ordering": ("sort_order", "id"),
            },
        ),
    ]
