# Generated by Django 5.2.12 on 2026-03-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_seed_cake_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogcake",
            name="slug",
            field=models.SlugField(max_length=160, unique=True, verbose_name="URL-имя"),
        ),
    ]
