# Generated by Django 5.2.12 on 2026-03-26 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_cake_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('inscription', models.CharField(blank=True, max_length=200, verbose_name='Надпись')),
                ('order_comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('delivery_comment', models.TextField(blank=True, verbose_name='Комментарий для курьера')),
                ('personal_data_consent', models.BooleanField(default=False, verbose_name='Согласие на обработку ПД')),
                ('options_total', models.PositiveIntegerField(default=0, verbose_name='Стоимость опций')),
                ('inscription_price', models.PositiveIntegerField(default=0, verbose_name='Стоимость надписи')),
                ('rush_fee', models.PositiveIntegerField(default=0, verbose_name='Наценка за срочность')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Итоговая стоимость')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('in_progress', 'Готовится'), ('delivering', 'В доставке'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('berry', models.ForeignKey(blank=True, limit_choices_to={'kind': 'berry'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='berry_orders', to='catalog.cakeoption', verbose_name='Ягоды')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('decor', models.ForeignKey(blank=True, limit_choices_to={'kind': 'decor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decor_orders', to='catalog.cakeoption', verbose_name='Декор')),
                ('level', models.ForeignKey(limit_choices_to={'kind': 'level'}, on_delete=django.db.models.deletion.PROTECT, related_name='level_orders', to='catalog.cakeoption', verbose_name='Количество уровней')),
                ('shape', models.ForeignKey(limit_choices_to={'kind': 'shape'}, on_delete=django.db.models.deletion.PROTECT, related_name='shape_orders', to='catalog.cakeoption', verbose_name='Форма')),
                ('topping', models.ForeignKey(limit_choices_to={'kind': 'topping'}, on_delete=django.db.models.deletion.PROTECT, related_name='topping_orders', to='catalog.cakeoption', verbose_name='Топпинг')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
    ]
