# Generated by Django 5.2.12 on 2026-03-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_confirmation_url_order_is_paid_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='landing_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Страница входа'),
        ),
        migrations.AddField(
            model_name='order',
            name='referrer',
            field=models.URLField(blank=True, verbose_name='Источник перехода'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=150, verbose_name='UTM campaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_content',
            field=models.CharField(blank=True, max_length=150, verbose_name='UTM content'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM medium'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM source'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_term',
            field=models.CharField(blank=True, max_length=150, verbose_name='UTM term'),
        ),
    ]
