# Generated by Django 5.2.12 on 2026-03-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_catalog_cakes'),
        ('orders', '0003_order_landing_path_order_referrer_order_utm_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='catalog_cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.catalogcake', verbose_name='Торт из каталога'),
        ),
        migrations.AlterField(
            model_name='order',
            name='level',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'level'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_orders', to='catalog.cakeoption', verbose_name='Количество уровней'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shape',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'shape'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shape_orders', to='catalog.cakeoption', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='topping',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'topping'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topping_orders', to='catalog.cakeoption', verbose_name='Топпинг'),
        ),
    ]
