# Generated by Django 5.2.12 on 2026-03-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_catalog_cake_alter_order_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_eta',
            field=models.CharField(blank=True, max_length=120, verbose_name='Интервал доставки'),
        ),
    ]
