# Generated by Django 5.2.12 on 2026-03-30 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_eta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('fixed', 'Фиксированная скидка'), ('percent', 'Скидка в процентах')], default='fixed', max_length=20, verbose_name='Тип скидки')),
                ('discount_value', models.PositiveIntegerField(verbose_name='Размер скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='complaint_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Жалоба создана'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_complaint',
            field=models.TextField(blank=True, verbose_name='Жалоба клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='Промокод'),
        ),
    ]
